/**
 * DALi Preview Animation Harness - Auto-generated by DALi Preview Extension
 * Do not edit manually.
 * Captures N frames at ANIMATION_FPS intervals then signals ANIM_DONE.
 */
#include <dali/dali.h>
#include <dali/public-api/adaptor-framework/capture.h>
#include <dali-ui-foundation/dali-ui-foundation.h>
#include <dali/devel-api/text-abstraction/font-client.h>

#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <cmath>
#include <cstdio>

using namespace Dali;
using namespace Dali::Ui;
using Dali::Ui::View;

static const float PREVIEW_WIDTH  = 720.0f;
static const float PREVIEW_HEIGHT = 1280.0f;
static const int   ANIMATION_DURATION = 2000;
static const int   ANIMATION_FPS      = 10;
static const int   TOTAL_FRAMES       = ANIMATION_DURATION * ANIMATION_FPS / 1000;

// === Click-to-code helper: tags an actor with a source line name ===
template<typename T>
T __tag(T obj, const char* name)
{
    obj.SetProperty(Dali::Actor::Property::NAME, Dali::String(name));
    return obj;
}

// === User preview code ===
View CreatePreviewUI()
{
// @preview-config: name="AnimTest" width=360 height=640 animation=true duration=2000 fps=10

// Simple animation preview sample:
// A colored box that animates via DALi Animation API.
// Captured as a multi-frame GIF (2s @ 10fps = 20 frames).

auto root = FlexLayout::New()
    .SetBackgroundColor(Color::BLACK);

auto box = View::New()
    .SetBackgroundColor(Color::BLUE)
    .SetSize(Vector2(100.0f, 100.0f))
    .SetParentOrigin(ParentOrigin::CENTER)
    .SetAnchorPoint(AnchorPoint::CENTER);

Animation anim = Animation::New(2.0f);
anim.AnimateTo(Property(box, Actor::Property::POSITION),
               Vector3(100.0f, 0.0f, 0.0f),
               AlphaFunction::EASE_IN_OUT);
anim.SetLooping(true);
anim.Play();

root.Add(box);
return root;

}

// === Scene graph metadata export ===

static std::string JsonEscapeStr(const std::string& s)
{
    std::string out;
    out.reserve(s.size() + 4);
    for(char c : s)
    {
        if      (c == '"')  out += "\\\"";
        else if (c == '\\') out += "\\\\";
        else if (c == '\n') out += "\\n";
        else if (c == '\r') out += "\\r";
        else if (c == '\t') out += "\\t";
        else if (static_cast<unsigned char>(c) < 0x20)
        {
            static const char hex[] = "0123456789abcdef";
            unsigned char uc = static_cast<unsigned char>(c);
            const char esc[7] = {'\\', 'u', '0', '0', hex[(uc >> 4) & 0xF], hex[uc & 0xF], '\0'};
            out += esc;
        }
        else                out += c;
    }
    return out;
}

static std::string ShortTypeName(const std::string& fullName)
{
    auto pos = fullName.rfind("::");
    return (pos != std::string::npos) ? fullName.substr(pos + 2) : fullName;
}

void CollectActorMetadata(Actor actor, std::ostringstream& json,
                          float pX, float pY, float pW, float pH,
                          bool isFirst = true)
{
    if(!isFirst) json << ",";

    Dali::String name = actor.GetProperty<Dali::String>(Actor::Property::NAME);
    Vector3 pos = actor.GetCurrentProperty<Vector3>(Actor::Property::POSITION);
    Vector3 size = actor.GetCurrentProperty<Vector3>(Actor::Property::SIZE);
    Vector3 anchor = actor.GetCurrentProperty<Vector3>(Actor::Property::ANCHOR_POINT);
    Vector3 parentOrigin = actor.GetCurrentProperty<Vector3>(Actor::Property::PARENT_ORIGIN);

    float w = size.x;
    float h = size.y;
    float x = pX + pW * parentOrigin.x + pos.x - w * anchor.x;
    float y = pY + pH * parentOrigin.y + pos.y - h * anchor.y;

    std::string typeName = ShortTypeName(std::string(actor.GetTypeName().CStr()));
    if(typeName.empty()) typeName = "Actor";

    bool    visible = actor.GetCurrentProperty<bool>(Actor::Property::VISIBLE);
    float   opacity = actor.GetCurrentProperty<float>(Actor::Property::OPACITY);
    Vector4 color   = actor.GetCurrentProperty<Vector4>(Actor::Property::COLOR);

    float safeOpacity = std::isfinite(opacity) ? opacity : 0.0f;
    float cr = std::isfinite(color.r) ? color.r : 0.0f;
    float cg = std::isfinite(color.g) ? color.g : 0.0f;
    float cb = std::isfinite(color.b) ? color.b : 0.0f;
    float ca = std::isfinite(color.a) ? color.a : 0.0f;

    json << "{\"name\":\"" << JsonEscapeStr(name.CStr()) << "\","
         << "\"type\":\"" << JsonEscapeStr(typeName) << "\","
         << "\"x\":" << x << ",\"y\":" << y << ","
         << "\"localX\":" << pos.x << ",\"localY\":" << pos.y << ","
         << "\"w\":" << w << ",\"h\":" << h << ","
         << "\"visible\":" << (visible ? "true" : "false") << ","
         << "\"opacity\":" << safeOpacity << ","
         << "\"properties\":{"
         << "\"color\":[" << cr << "," << cg << "," << cb << "," << ca << "]"
         << "}";

    uint32_t childCount = actor.GetChildCount();
    if(childCount > 0)
    {
        json << ",\"children\":[";
        for(uint32_t i = 0; i < childCount; i++)
        {
            CollectActorMetadata(actor.GetChildAt(i), json, x, y, w, h, (i == 0));
        }
        json << "]";
    }
    json << "}";
}

void ExportSceneMetadata(Actor root, const char* metadataPath, float winW, float winH)
{
    Vector3 rootSize = root.GetCurrentProperty<Vector3>(Actor::Property::SIZE);
    float rW = rootSize.x;
    float rH = rootSize.y;

    std::ostringstream json;
    json << "{\"root\":{\"name\":\"RootLayer\","
         << "\"x\":0,\"y\":0,\"w\":" << rW << ",\"h\":" << rH;

    uint32_t childCount = root.GetChildCount();
    if(childCount > 0)
    {
        json << ",\"children\":[";
        for(uint32_t i = 0; i < childCount; i++)
        {
            CollectActorMetadata(root.GetChildAt(i), json, 0.0f, 0.0f, rW, rH, (i == 0));
        }
        json << "]";
    }
    json << "}}";

    std::ofstream out(metadataPath);
    out << json.str();
}

class PreviewApp : public ConnectionTracker
{
public:
  PreviewApp(Application& app) : mApp(app), mFrameIndex(0)
  {
    app.InitSignal().Connect(this, &PreviewApp::OnInit);
  }

  void OnInit(Application& app)
  {

    Window window = app.GetWindow();
    window.SetBackgroundColor(Vector4(0.1f, 0.1f, 0.12f, 1.0f));

    View root = CreatePreviewUI();
    window.Add(root);

    // Wait for layout stabilisation before starting frame capture
    mLayoutTimer = Timer::New(500);
    mLayoutTimer.TickSignal().Connect(this, &PreviewApp::OnLayoutReady);
    mLayoutTimer.Start();
  }

  bool OnLayoutReady()
  {
    TriggerNextFrame();
    return false; // one-shot
  }

  void TriggerNextFrame()
  {
    if(mFrameIndex >= TOTAL_FRAMES)
    {
      std::cout << "ANIM_DONE:" << TOTAL_FRAMES << std::endl;
      mApp.Quit();
      return;
    }

    char framePath[512];
    std::snprintf(framePath, sizeof(framePath), "/tmp/frames/frame_%03d.png", mFrameIndex);

    Window window = mApp.GetWindow();
    if(mCapture)
    {
      mCapture.FinishedSignal().Disconnect(this, &PreviewApp::OnFrameCaptured);
    }
    Capture capture = Capture::New();
    capture.FinishedSignal().Connect(this, &PreviewApp::OnFrameCaptured);
    mCapture = capture;
    capture.Start(Actor(window.GetRootLayer()),
                  Vector2(PREVIEW_WIDTH, PREVIEW_HEIGHT),
                  Dali::String(framePath),
                  Vector4(0.1f, 0.1f, 0.12f, 1.0f));
  }

  void OnFrameCaptured(Capture capture, Capture::FinishState state)
  {
    if(state == Capture::FinishState::SUCCEEDED)
    {
      mFrameIndex++;
      std::cout << "FRAME:" << mFrameIndex << "/" << TOTAL_FRAMES << std::endl;
      if(mFrameIndex == 1)
      {
        Window window = mApp.GetWindow();
        ExportSceneMetadata(Actor(window.GetRootLayer()), "/tmp/preview_metadata.json", PREVIEW_WIDTH, PREVIEW_HEIGHT);
      }
      // Schedule next frame after the configured interval
      uint32_t intervalMs = static_cast<uint32_t>(1000 / ANIMATION_FPS);
      if(intervalMs < 1) intervalMs = 1;
      mCaptureTimer = Timer::New(intervalMs);
      mCaptureTimer.TickSignal().Connect(this, &PreviewApp::OnCaptureInterval);
      mCaptureTimer.Start();
    }
    else
    {
      std::cerr << "FRAME_CAPTURE_FAILED:" << mFrameIndex << std::endl;
      // Skip failed frame and continue
      mFrameIndex++;
      TriggerNextFrame();
    }
  }

  bool OnCaptureInterval()
  {
    TriggerNextFrame();
    return false; // one-shot
  }

private:
  Application& mApp;
  int          mFrameIndex;
  Timer        mLayoutTimer;
  Timer        mCaptureTimer;
  Capture      mCapture;
};

int main(int argc, char* argv[])
{
  Application app = Application::New(&argc, &argv, "", Application::OPAQUE);
  UiConfig::New().Apply();
  PreviewApp preview(app);
  app.MainLoop();
  return 0;
}
