/**
 * DALi Preview Harness - Auto-generated by DALi Preview Extension
 * Do not edit manually.
 */
#include <dali/dali.h>
#include <dali/public-api/adaptor-framework/capture.h>
#include <dali-ui-foundation/dali-ui-foundation.h>

#include <iostream>

using namespace Dali;
using namespace Dali::Ui;
using Dali::Ui::View;

static const float PREVIEW_WIDTH  = 1024.0f;
static const float PREVIEW_HEIGHT = 600.0f;

// === User preview code ===
View CreatePreviewUI()
{
return View::New()
    .SetBackgroundColor(UiColor(0xFFFF00))
    .SetRequestedWidth(200.0f)
    .SetRequestedHeight(200.0f);

}

class PreviewApp : public ConnectionTracker
{
public:
  PreviewApp(Application& app) : mApp(app)
  {
    app.InitSignal().Connect(this, &PreviewApp::OnInit);
  }

  void OnInit(Application& app)
  {
    Window window = app.GetWindow();
    window.SetBackgroundColor(Vector4(0.1f, 0.1f, 0.12f, 1.0f));

    View root = CreatePreviewUI();
    window.Add(root);

    mTimer = Timer::New(500);
    mTimer.TickSignal().Connect(this, &PreviewApp::OnTimer);
    mTimer.Start();
  }

  bool OnTimer()
  {
    Window window = mApp.GetWindow();
    Capture capture = Capture::New();
    capture.FinishedSignal().Connect(this, &PreviewApp::OnCaptured);
    mCapture = capture;
    capture.Start(Actor(window.GetRootLayer()),
                  Vector2(PREVIEW_WIDTH, PREVIEW_HEIGHT),
                  Dali::String("/tmp/preview.png"),
                  Vector4(0.1f, 0.1f, 0.12f, 1.0f));
    return false;
  }

  void OnCaptured(Capture capture, Capture::FinishState state)
  {
    if(state == Capture::FinishState::SUCCEEDED)
      std::cout << "OK:/tmp/preview.png" << std::endl;
    else
      std::cerr << "CAPTURE_FAILED" << std::endl;
    mApp.Quit();
  }

private:
  Application& mApp;
  Timer        mTimer;
  Capture      mCapture;
};

int main(int argc, char* argv[])
{
  Application app = Application::New(&argc, &argv, "", Application::OPAQUE);
  UiConfig::New().Apply();
  PreviewApp preview(app);
  app.MainLoop();
  return 0;
}
